---
freebsd_instance:
  image_family: freebsd-14-2

task:
  install_script:
    - pkg install -y bash curl git gmake gnugrep openjdk21 zip
    - mount -t fdescfs fdesc /dev/fd
    - mount -t procfs proc /proc
    - pw useradd -n jtreg

  build_script: >
    su jtreg -c "echo \"[*] Running as user: $(whoami)\" &&
    cd ${HOME} &&
    bash make/build.sh --jdk /usr/local/openjdk21"

  test_script: su jtreg -c 'cd ${HOME} && bash build/make.sh test'
