---
freebsd_instance:
  image_family: freebsd-14-2

task:
  install_script:
    - pkg install -y bash curl git gmake gnugrep openjdk21 zip
    - mount -t fdescfs fdesc /dev/fd
    - mount -t procfs proc /proc

  build_script:
    - echo "[*] Running as user: $(whoami)"
    - bash make/build.sh --jdk /usr/local/openjdk21

  test_script:
    - bash build/make.sh test
